### ISSUE TITLE
Can't get initial value of non-observable resources from the REST API server

### ISSUE THREAD

**Issue by ttzeng** [01org/SmartHome-Demo#101]
The docker image used to get the states of OCF resources from the iot-rest-api-server with "&obs=1" in query URI like this:
http://192.168.1.107:8000/api/oic/a/pir?di=2282f9a5-9d9a-40f2-a9c4-efb3616124c6&obs=1
the server will return the initial value of the target resource and continue send out updates on state changes:
{"id":"motionSensor","value":false}{"id":"motionSensor","value":false}....

However OCF also allows non-observable resources, the docker image won't get the initial state of those non-observable resources using the above mechanism:
http://192.168.1.107:8000/api/oic/brillo/mp3player/volume?di=72dc1ccf-1637-42e7-aab8-a258a2487fd1&obs=1

The image will be waiting for the updates from the API server, but that won't happen as non-observable resources won't notify the clients on property changed. Since the resource is non-observable, the docker image need to query its state without "&obs=1" in the URI:
http://192.168.1.107:8000/api/oic/brillo/mp3player/volume?di=72dc1ccf-1637-42e7-aab8-a258a2487fd1
{"mute":true,"volume":0}

**Comment by gvancuts** [comment]
@poussa @ichbinblau , do I understand this one correctly that the proper course of action is to wait for an updated `iot-rest-api-server` that will include a property stating whether a resource can be observed and update the cloud portal to adjust its behaviour based on that?

**Comment by ichbinblau** [comment]
@gvancuts that's also my understanding. The portal as the http client would adjust its request method by the observable property returned by iot-rest-api-server .

**Comment by poussa** [comment]
@gvancuts Yes, one need to have the iot-rest-api-server from the master, which include patch to enable this behavior: https://github.com/01org/iot-rest-api-server/commit/ce21be84dc2d3a03fb99b0756141e29fcbbcb625

It is currently only in the master, not released via npm. We don't have to include this for the hackathon config since it is not tested at all yet.

**Comment by gvancuts** [comment]
Completely agree. I'll assign this to you for now so we can update the `iot-rest-api-server` when the time is right (i.e. once it's been tested and is released via npm).

**Comment by nagineni** [comment]
@ichbinblau could you please adjust the portal code and check with the iot-rest-api-server from maser https://github.com/01org/iot-rest-api-server?

**Comment by ichbinblau** [comment]
Hi, @nagineni . I wrote down the respective ways to handle the resources in different situations. Would you check whether it is correct and answer the question below? Thank you. 

a) Resource that is discoverable but not observable:
"p": {"bm": 1, "sec": false}
**Solution: start a regular job to pull data at a time interval.** 

b) Resource that is observable but not discoverable:
"p": {"bm": 2, "sec": false}
**Question: if a resource is not discoverable, how can I know when the resource is alive?**

c) Resource that is discoverable and observable:
"p": {"bm": 3, "sec": false}
**Solution: create thread to obverse the resource**

**Comment by nagineni** [comment]
> b) Resource that is observable but not discoverable:
> "p": {"bm": 2, "sec": false}
> Question: if a resource is not discoverable, how can I know when the resource is alive?

The device doesn't expose the resources that are not discoverable, so you don't see it at all.

**Comment by gvancuts** [comment]
Is this issue still valid?

**Comment by ttzeng** [comment]
This no long valid as Theresa added the code, no "&obs=1" was included in the query to non-observable resources.

**Comment by ichbinblau** [comment]
Yes, the code has been updated to treat observable and non-observable resource separately.  I did not see this problem anymore.

**Comment by gvancuts** [comment]
Thanks @ttzeng , closing this then.
