### ISSUE TITLE
Cloud Portal not displaying the correct values

### ISSUE THREAD

**Issue by gvancuts** [01org/SmartHome-Demo#105]
I ran some of the known devices (such as `temperature`, `light`, `solar`) in simulation mode but the actual value of the devices was not displayed in their respective widgets on the cloud portal (in a Docker container). I couldn't read what it said for `solar` but `temperature` was showing **NaN** instead of a value. I could see from the Docker container traces that it was getting values and we could see those from a browser tab (using `localhost/api/oic/a/temperature?di=<device ID>`). This is using code from the current master branch (fd4e84f). The Docker container was pulled from Docker Hub directly.

@ttzeng , @ichbinblau , do you have any suggestion?

**Comment by ttzeng** [comment]
@gvancuts you might clear the browser cache and render the page again by CTRL-F5 for a try.

**Comment by ichbinblau** [comment]
Thanks @ttzeng for the test.  Hi, @gvancuts. I think Tonny is right. You may want to clear the browser cache and try it one more time. We met the same NaN issue before and a cache cleanup solved the prob.

**Comment by gvancuts** [comment]
I'll try this once I get back at my desk (that'll be the week after next at the earliest). I'm pretty sure that in all the testing I did, I also tried with Firefox (as an alternative to Google Chrome), we tried that on different machines too.

@uhofemei , could you test this on your side too (staging environment). Using the cloud portal in a container should be exercised and tested on a regular basis.

**Comment by uhofemei** [comment]
@gvancuts  yes will do.

**Comment by qiuzhong** [comment]
I did some tests for this issue. 
Here is my configuration:
* Clear All History in Firefox, choose <strong>Time range to clear: "Everything"</strong>
* OCF servers: [fd4e84f](https://github.com/01org/SmartHome-Demo/commit/fd4e84f4bca60bbc15a59553b8eba06b1c9e549e) (simulated)
* Web portal: I didn't get it from Docker hub, I built it with the latest master branch [92322e3](https://github.com/01org/SmartHome-Demo/commit/92322e3aa412e3dbad35b74a7f25dc0d7f48775e)

In my test, <code>temperature</code>, <code>light</code>, <code>solar</code> all can be displayed well on the web portal.

But then I encountered the issue @gvancuts metioned:
* I stopped the web portal container and started an old web portal docker container (It's image is pulled from Docker hub before, I didn't try the latest image from docker hub as the it's very slow to pull from docker hub here).  After login the web portal, I didn't see any devices.
* Then stop the old docker image container and restart the local web portal container. <strong>This time I didn't clear the browser history</strong> and I got a <code>NaN</code>.
* Clear the history, the devices can be displayed well again.

**Comment by qiuzhong** [comment]
I just pulled the latest smarthome2cloud/smarthome-demo from docker hub on a new Ubuntu host.
There is no history of accessing the web portal for the web browser on that host. 

And I did a test.
I have to say, I didn't encounter such <code>NaN</code> issue. <code>temperature</code>, <code>light</code>, <code>solar</code> all can be displayed well on the web browser.

**Comment by uhofemei** [comment]
Using the latest smarthome2cloud/smarthome-demo container I see values from the non-simulated temperature and light sensor in my IoTivity 1.2.0 staging environment. I can't get to the cloud portal on port 3030 yet due to missing port forwarding rules. I will fix that tomorrow and report back.

**Comment by gvancuts** [comment]
Thank you both for you testing. I don't have the environment anymore and I'm currently travelling so it will take a little while before I can get back to this issue. I'll definitely try cleaning the history of the browser next time to see if it helps.

**Comment by uhofemei** [comment]
I think we can close the issue? I'm trying to clean up the issue tracker before our next sync meeting on Tuesday :)
