### ISSUE TITLE
Introduce a command-line argument to start OCF JS server in simulation mode

### ISSUE THREAD

**Issue by gvancuts** [01org/SmartHome-Demo#106]
We should have a command-line parameter (e.g. `--simulation`) to start any of the OCF JS servers in simulation mode. They currently do that when some of the low-level libraries (such as `noble` or `mraa`) are not available but a switch forcing that irrespective of that would be desirable.

**Comment by nagineni** [comment]
:+1:

**Comment by gvancuts** [comment]
This can be closed as #116 and #112 have both been merged
