### ISSUE TITLE
Smart Solar Panel subsystem needs to be rebuilt

### ISSUE THREAD

**Issue by gvancuts** [01org/SmartHome-Demo#111]
The Edison board we used for the Smart Solar Panel broke down at the last event (and a connector pin broke too). The HW was replaced by I failed at my attempts to rebuild the functionality. The new HW is in place in the demo kit but a functional image needs to be reflashed onto it.

We should also put a new spare Edison board in the kit (and remove the one in there that is defective).

**Comment by mjkadera** [comment]
Any update on this?

**Comment by uhofemei** [comment]
90% complete.

**Comment by mjkadera** [comment]
Services are running, but the test for functionality is still pending

**Comment by mjkadera** [comment]
@uhofemei , any progress on this request?

**Comment by uhofemei** [comment]
This one is in an odd state. The solar panel OCF server starts, but it never registers with the OCF client gateway. I will replace the actuator and PWM controller board on Monday to see if we are dealing with broken hardware.

**Comment by uhofemei** [comment]
I rebuilt this feature and the solar panel actuator has power. We have no way to control it as Tonny's companion app doesn't see the solar panel resource and Salvatore's smart home control app doesn't work with IoTivity 1.2.0.

**Comment by mjkadera** [comment]
This is built and pending testing. @uhofemei will run the panel in simulation mode. @ttzeng will recompile the application and provide it to ulf.

**Comment by uhofemei** [comment]
The solar panel is functional in simulation mode. It can currently be trigger by using a script on the gateway that activates the simulation mode.
