### ISSUE TITLE
Crashed when launching ambient_light.js

### ISSUE THREAD

**Issue by qiuzhong** [01org/SmartHome-Demo#118]
## Environments
* MinnowBoard Turbot
* [IoT-Refkit image#build 135](http://iot-ref-kit.ostc.intel.com/download/builds/intel-iot-refkit_master/2017-03-01_10-58-06-build-135/images/intel-corei7-64/refkit-image-gateway-intel-corei7-64.wic)

It crashed when launching ambient_light.js, see the error log:

```
# export NODE_DEBUG=ambient_light; node ambient_light.js   
/home/root/ocf-servers/js-servers/helper-function/mraa_MinnowBoard_ADC.js:36
        this.ads1115 = new this.upm.ADS1115(0, 0x48);
                       ^

Error: Illegal arguments for construction of _exports_ADS1115
    at Error (native)
    at new Aio (/home/root/ocf-servers/js-servers/helper-function/mraa_MinnowBoard_ADC.js:36:24)
    at setupHardware (/home/root/ocf-servers/js-servers/ambient_light.js:58:17)
    at Object.<anonymous> (/home/root/ocf-servers/js-servers/ambient_light.js:152:5)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
```

**Comment by gvancuts** [comment]
This can also easily be reproduced on different HW platform and OS. I can reproduce this using a NUC loaded with Ubuntu 16.04 as an example (`mraa` was installed on that OS using `npm install mraa`).

**Comment by ttzeng** [comment]
I believe this requires external ADC module like [ADS1015](https://software.intel.com/en-us/iot/hardware/sensors/12-bit-adc-with-integrated-mux-pga-comparator-oscillator-and-reference) or [ADS1115](https://software.intel.com/en-us/iot/hardware/sensors/16-bit-adc-with-integrated-mux-pga-comparator-oscillator-and-reference) connected to your board via I2C bus, did you test with any ADC module?

**Comment by uhofemei** [comment]
This is odd. There is code in ambient_light.js that should check if an ADC is available and not load the helper function to use UPM if that's the case. See here: 

https://github.com/01org/SmartHome-Demo/blob/master/ocf-servers/js-servers/ambient_light.js#L31

and here as for what it does:
https://iotdk.intel.com/docs/master/mraa/namespacemraa.html#aab42dc89e7de2ebb8c7530c4868bc933

**Comment by gvancuts** [comment]
You are correct @ttzeng. This bug is about the app crashing when it's not connected. A better behaviour would be to error out and not crash. There is little error-checking in the code that was added and I guess that's why it's not catching it and exiting cleanly.

You are also correct @uhofemei , the code only loads the helper if there is not existing ADC attached... but it then unconditionally loads the module for the external ADC module, without any check as to whether it was found and/or initialized properly. That's what this bug is about.

**Comment by uhofemei** [comment]
I can enhance the UPM helper function with try/catch and print an error message indicating that no ADC was found and the simulation mode should be used on MinnowBoard Turbot. I can use your simulation mode argument code for that. Sound good?

**Comment by gvancuts** [comment]
That sounds good. Thanks

**Comment by uhofemei** [comment]
@qiuzhong could you try my change please? This should cause MRAA to report back that no ADC is available on the MinnowBoard. At the same time the ambient_light.js OCF server code should work with the Edison. I will test if the code works as expected if an ADS1515 chip has been installed on the MinnowBoard tomorrow. 
https://github.com/uhofemei/SmartHome-Demo/commit/e644dc8e51954e186a338953203a4bf8ee8b5bcb

**Comment by qiuzhong** [comment]
Here are my test results based on [uhofemei@e644dc8](https://github.com/uhofemei/SmartHome-Demo/commit/e644dc8e51954e186a338953203a4bf8ee8b5bcb)
* MinnowBoard Turbot without ADC
  ```
  # export NODE_DEBUG=ambient_light; node ambient_light.js
  AMBIENT_LIGHT 697: No mraa module:  Unexpected token catch
  AMBIENT_LIGHT 697: Automatically switching to simulation mode
  /home/root/SmartHome-Demo-uhofemei/ocf-servers/js-servers/ambient_light.js:58
      sensorPin = new mraa.Aio(3);
                  ^
  
  Error: Invalid AIO pin specified - do you have an ADC?
      at Error (native)
      at setupHardware (/home/root/SmartHome-Demo-uhofemei/ocf-servers/js-servers/ambient_light.js:58:17)
      at Object.<anonymous> (/home/root/SmartHome-Demo-uhofemei/ocf-servers/js-servers/ambient_light.js:153:5)
      at Module._compile (module.js:409:26)
      at Object.Module._extensions..js (module.js:416:10)
      at Module.load (module.js:343:32)
      at Function.Module._load (module.js:300:12)
      at Function.Module.runMain (module.js:441:10)
      at startup (node.js:139:18)
      at node.js:974:3  
  ```
  It can tell users ADC not found. But I don't think it runs in simulation mode in function [<code>setupHardware</code>](https://github.com/uhofemei/SmartHome-Demo/blob/e644dc8e51954e186a338953203a4bf8ee8b5bcb/ocf-servers/js-servers/ambient_light.js#L55).
  I think this is because <code>var mraa = require('mraa');</code> succeeds,  so<code>mraa</code> is not null even there is no ADC. Then the if-condition <code>!mraa</code> simply returns <strong>false</strong>. So it doesn't run in simulation mode though the simulationMode is set to true.

* Edison
  It can work well with real sensor data.
  ```
  # export NODE_DEBUG=ambient_light; ocf-util.node ambient_light.js
  AMBIENT_LIGHT 1237: Create Illuminance sensor resource.
  AMBIENT_LIGHT 1237: register() resource successful
  AMBIENT_LIGHT 1237: Send the lux value:  25.58
  SWITCH 1108: Send the response:  true
  AMBIENT_LIGHT 1237: Send the lux value:  25.3
  AMBIENT_LIGHT 1237: Send the lux value:  25.16
  AMBIENT_LIGHT 1237: Send the lux value:  25.44
  AMBIENT_LIGHT 1237: Send the lux value:  25.58
  ^CAMBIENT_LIGHT 1237: Delete Illuminance sensor Resource.
  AMBIENT_LIGHT 1237: unregister() resource successful
  ```

**Comment by mjkadera** [comment]
Based on the March 14 meeting 
ADC detection on the MinnowBoard is not currently an easy to use solution. No way to implement proper error checking in the code. QA is stating the code is still crashing. 

The code was created to support the Hackathon and we recommend to use anther board solution (Edison or Joule) . The recommendation is to remove the code.

**Comment by uhofemei** [comment]
Pull request to remove the code has been created. https://github.com/01org/SmartHome-Demo/pull/121

**Comment by uhofemei** [comment]
As the PR for this issue has been merged, I'm closing the issue to clean things up
