### ISSUE TITLE
Make buzzer resource controllable remotely via the cloud portal

### ISSUE THREAD

**Issue by uhofemei** [01org/SmartHome-Demo#122]
Currently the buzzer generates a notification in the cloud app if it has been triggered. I think it would be better to make it controllable remotely. Reasons for this are many: It would allow homeowners to trigger an alarm to let folks at home know to evacuate in case of an emergency for example.

**Comment by gvancuts** [comment]
I'm assuming when you say 'controllable remotely', you mean from the cloud portal, is that correct?

**Comment by uhofemei** [comment]
Yep. Title updated to make it more clear.

**Comment by mjkadera** [comment]
Development is done. @ichbinblau will submit a pull request.
