### ISSUE TITLE
Enhance `smarthome-sensors` Docker container: selectively start some of the OCF servers

### ISSUE THREAD

**Issue by gvancuts** [01org/SmartHome-Demo#127]
We should enhance the `smarthome-sensors` Docker container by providing a mechanism to allow to selectively choose which OCF servers to start (in simulation mode) inside any container running the image. The exact mechanism on how to do that is to be defined, it could be a shared file listing the OCF servers to start, or a list of them passed as arguments, etc.

**Comment by mjkadera** [comment]
@gvancuts to provide the recommendation on the code and complete the pull request. 

This is blocked until the PR and testing is complete.

**Comment by mjkadera** [comment]
@ichbinblau will send the request for the validation to the team contact

**Comment by mjkadera** [comment]
@gvancuts to complete the PR review
