### ISSUE TITLE
Develop JavaScript sensors (OCF server) based on Zephyr

### ISSUE THREAD

**Issue by gvancuts** [01org/SmartHome-Demo#131]
We should have a few sensors based on ZJS, the [JavaScript* Runtime for Zephyr™ OS](https://github.com/01org/zephyr.js) and [iotivity-constrained](https://github.com/iotivity/iotivity-constrained). The exact list of sensors to be developed is still TBD.

**Comment by uhofemei** [comment]
I've been discussing this in more detail with James Prestwood. The way the ZJS implementation for multiple sensors works is that it's using the property value to access each sensor exposed via a single resource. I don't think this solution is OCF compliant as it entails that the OCF client observing the OCF server must "know" there are multiple sensors "hidden" behind a single resource. There is no way to discover them individually. James was saying we need to discuss a better solution in more detail with @poussa.

**Comment by gvancuts** [comment]
With the latest PR #139 being merged, we now have a number of OCF servers available based on ZJS in `ocf-servers/zjs-servers`. I therefore propose that close this enhancement as done. If additional Smart Devices (OCF server based on ZJS) are desirable, we can always open a new feature request.

Any disagreement?

As a side note, we may want to re-organize a bit the directory structure, we have native Zephyr-based IoT devices in `sensors`, JavaScript (node.js) ones in `ocf-servers/js-servers` and ZJS ones in `ocf-servers/zjs-servers`. How about we create the following structure instead?
```
/iot-devices/
    |-> js-servers/
    |-> zjs-servers/
    |-> zephyr-servers/
```

**Comment by gvancuts** [comment]
No disagreements were voiced... closing this! (we can discuss the folder organization separately)
