### ISSUE TITLE
Companion app doesn't see solar panel resource

### ISSUE THREAD

**Issue by uhofemei** [01org/SmartHome-Demo#132]
There is no way to control the solar panel actuator from the companion app.

**Comment by uhofemei** [comment]
I can't seem to assign this bug to Tonny. His GitHub username doesn't resolve.

**Comment by ttzeng** [comment]
@uhofemei the solar panel is supported by [the new companion app](https://github.com/ttzeng/android-apps/commit/df3ddf2682f218c95605183be65ecb79739e93ee), both [x86](https://drive.google.com/open?id=0B8-BcoYPJr2LaWxHM1lBRmktYzg) and [armeabi](https://drive.google.com/open?id=0B8-BcoYPJr2LZkNFemxpckU3cm8) flavors are available for your evaluation. Thanks.

**Comment by uhofemei** [comment]
Thanks @ttzeng. I will give it a try :)
