### ISSUE TITLE
Temperature reading is too high

### ISSUE THREAD

**Issue by uhofemei** [01org/SmartHome-Demo#134]
The temperature reported by the sensor connected to the Arduino 101 reads too high (124 F average in the lab.)

**Comment by andersqiu** [comment]
If you use the Grove Shield, please check the Vcc switch of the Grove Shield. It should be 3.3V. This is from the [README](https://github.com/01org/SmartHome-Demo/tree/master/sensors/ocf_multi_sensors#sensor-wiring):
> Since the Arduino 101 works at 3.3V and the sensors support the voltage, don't forget to turn the switch on the Grove base shield to 3V3 position.

**Comment by qiuzhong** [comment]
If you use the Grove Base Shield, please check the Vcc switch. It should use the 3.3V.
In the [README](https://github.com/01org/SmartHome-Demo/tree/master/sensors/ocf_multi_sensors#sensor-wiring) of ocf_multi_sensors:
>  Since the Arduino 101 works at 3.3V and the sensors support the voltage, don't forget to turn the switch on the Grove base shield to 3V3 position.

**Comment by qiuzhong** [comment]
I got 126 F in the lab before when the Grove Shield Vcc switch was turned to 5V.

**Comment by qiuzhong** [comment]
From [PR#129 comment](https://github.com/01org/SmartHome-Demo/pull/129#issuecomment-296626681)
>  We should keep using 3.3V since the analog ones (temperature, light) will take wrong sensing values from input with voltage value higher than the support range (0 - 3.3V).

**Comment by uhofemei** [comment]
Thanks @qiuzhong. I will change the setting to 3.3V.

**Comment by uhofemei** [comment]
I have the shield set to 3.3V and the temperature sensor still reads too high > 130 F in the lab.

**Comment by gvancuts** [comment]
We are still facing this issue with the switch set to 3.3V, we will try with a different physical sensor next.

**Comment by uhofemei** [comment]
Swapping out the temperature sensor didn't solve the issue. It's still reading ~ 128 F.

**Comment by qiuzhong** [comment]
Tested again, the temperature sensor reading is normal in the lab. The temperature sensor I used is [Grove Temperature Sensor v1.2](http://wiki.seeed.cc/Grove-Temperature_Sensor_V1.2/).
* 3.3V:
  ```
  {"temperature":72.5468666,"units":"F","range":"-40, 257"}
  ```
* 5V:
  ```
  {"temperature":119.1563258,"units":"F","range":"-40, 257"}
  ```

**Comment by kiendinh** [comment]
@uhofemei Do you have another Grove shield to try? It's possible that the switch is not actually set to 3.3V even though it is set to.

**Comment by uhofemei** [comment]
Using ZJS and the external Grove temperature sensor the reported value is accurate.
