### ISSUE TITLE
Improve companion app UI

### ISSUE THREAD

**Issue by uhofemei** [01org/SmartHome-Demo#135]
The companion app UI running in landscape mode uses a rather small font and only spans across 1/6th of the screen size on a high resolution smart phone, such as the Nexus 6P. Is there a way to adjust the font size used according to the device screen resolution?
![screenshot_20170427-114707](https://cloud.githubusercontent.com/assets/933047/25625829/7092f6e0-2f12-11e7-96ae-b4a816f1faed.png)

**Comment by gvancuts** [comment]
@ttzeng , can you please take a look?

**Comment by ttzeng** [comment]
I'd propose the near term solution to have the Android framework [auto adjust the text size of the control menu based on the screen size of the device](https://github.com/ttzeng/android-apps/commit/b6a74dbf15c9d1e9715ee37d5fcf5c88f3b8eaa5), and design a new UX to accommodate both webview fragment and resource view fragment across multiple screen size in portrait and landscape modes in longer term.  The current prebuilt images ([x86](https://drive.google.com/open?id=0B8-BcoYPJr2LaWxHM1lBRmktYzg), [armeabi](https://drive.google.com/open?id=0B8-BcoYPJr2LZkNFemxpckU3cm8)) already incorporate this change, I've verify on AVD emulators (Nexus4, Nexus6), please give it a try.

**Comment by uhofemei** [comment]
With this app the font is bigger but the ratio how much real estate is allocated on the screen by the app seems to be fixed. Can we make it bigger so that text does't have to wrap?
![screenshot_20170504-122717](https://cloud.githubusercontent.com/assets/933047/25714900/7013ba7c-30ae-11e7-8daa-c5aaed7605a0.png)

**Comment by ttzeng** [comment]
The control menu currently takes [1/4](https://github.com/ttzeng/android-apps/blob/master/smarthome_companion/src/main/res/layout/activity_main.xml#L38-L48) of the real estate on the screen, if it becomes wider, the resource cards may have no sufficient real estate for displaying the resource URI, especially resources may report lengthy host name...

**Comment by uhofemei** [comment]
Landscape/portrait orientation works, but in portrait the app only takes up 30% of the center of the screen and the top and bottom half are black. The solar panel feature works well! 👍

**Comment by uhofemei** [comment]
OK understood. It looks better this way already.

**Comment by gvancuts** [comment]
The latest version of the application provided by @ttzeng fixes this issue. Closing.
