### ISSUE TITLE
Enhance instructions on how to run the Cloud & Analytics components (focussed on Docker)

### ISSUE THREAD

**Issue by gvancuts** [01org/SmartHome-Demo#145]
We have some information in this README.md file: `smarthome-web-portal/tools/docker/README.md` that explain how to run the cloud somponents in Docker. But we need to:
1. Update those instructions (they're slightly out of date, e.g. the Docker Hub container is now called smarthome-cloud instead of smarthome-demo)
2. Add `sudo` to all `docker` commands and add the same paragraph about security considerations on how to run Docker as a standard user
3. Add a note explaining that an internet connection is *required* (see #143 for more details)
4. Refer to that Cloud `smarthome-web-portal/tools/docker/README.md` more explicitly in the repo top-level `README.md`

**Comment by uhofemei** [comment]
Docker doesn't need to be run with sudo. Instead the system user must be added to the docker group.

**Comment by gvancuts** [comment]
> Docker doesn't need to be run with sudo. Instead the system user must be added to the docker group.

Correct, and that's accounted for in the new test that this PR introduces so I'm good with the proposal. Do you have any concerns on the new text?

**Comment by uhofemei** [comment]
The new PR adds sudo to all docker commands and this isn't needed. The system user should be added to the docker group using the command sudo usermod -aG docker $USER. After that docker pull, docker run, etc. can run unprivileged fine.

**Comment by gvancuts** [comment]
@mmccool's point in PR #144 is that doing so represents a security hole and hence his approach is that we should instead recommend using `sudo`. The option to set things up so you don't need to do it is still available and the text indicates that (also pointing out that it compromises your system's security). I think his approach makes sense. We should also make sure that the various README.md's in the tree are consistent in what we recommend.

**Comment by mmccool** [comment]
I did consider adding instructions to add the user to the "docker" group, which would have been the alternative to using sudo (and consisent with much of the docker documentation...).   However, when I looked into it, apparently this is equivalent to giving root privileges to that user.   See warnings under
https://docs.docker.com/engine/installation/linux/linux-postinstall/
and
https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface

Sudo is safer, since it requires a password to use.   But if someone is cutting and pasting commands, and they have set up the system to not use sudo, they can just omit that part if they want.   If someone has NOT set up their system to allow docker to use sudo, then they won't have to type it (or get an error they may or may not be able to figure out).

**Comment by mmccool** [comment]
So... now trying to get the cloud web portal to run.   I have it "running" (sort of) but can't yet log in as a regular user.  It looks like the "ostro/ostro" credentials noted in the instructions are out of date.   In fact the login page doesn't even want to accept those credentials as valid (it seems "ostro" is not considered a well-formed password by the input checker for the password input field).  Also, under the admin page there is no "ostro" user (just a "dev" and a "OTC" user...).

Going to dive into the code now to see if I can sort these issues out...

**Comment by gvancuts** [comment]
These were changed when PR #125 got merged (and I wish I had remembered to ask for the README.md to be updated as well... :(

New passwords are:
* dev -> P@ssw0rd
* OTC -> !otivity

https://github.com/01org/SmartHome-Demo/pull/125/files#diff-b2d92e484b73f774b4953e429183f45c

**Comment by uhofemei** [comment]
https://github.com/01org/SmartHome-Demo/pull/146

**Comment by mmccool** [comment]
OK, thanks.  I also managed to get it to work by creating a new user, but it would be good to update the docs, of course.

**Comment by gvancuts** [comment]
Are we referencing `https` instead of `http` in our documentation somewhere?

It is possible to switch to `https` by changing [this line](blob/master/gateway/start-gateway-in-docker.sh#L14) adding `-s` as an argument (thinking about it, it would be a good idea to make this a parameter that could be passed to the Docker container instead of having to rebuild a new container for this... I'll file a feature request for this).

Which physical setup tutorial are you referring to (which does not talk about the simulated set-up), is it the one on https://01.org/smarthome?

Thanks!

**Comment by gvancuts** [comment]
@mmccool I have created PR #147 that, **once merged**, will allow you to easily switch to https on the gateway, e.g.:
```
$ sudo docker run smarthome2cloud/smarthome-gateway -s
```

**Comment by gvancuts** [comment]
PR #155 was merged, closing this.
