### ISSUE TITLE
New user/gateway not persistent across a container restart

### ISSUE THREAD

**Issue by gvancuts** [01org/SmartHome-Demo#152]
You can add a new user and gateway through the Admin portal but these are not persistent in case you stop/restart the smarthome-cloud container. We should find a way of making those persistent.

**Comment by ichbinblau** [comment]
Hi, @gvancuts. The user and gateway info are saved in the MySQL database which should be persistent during the container's life cycle.  If the container/database is destroyed, the data will be gone.  

From the local test, the new user/gateway was still there after I restarted or stopped and started the container.  I used `docker restart <container-id>` to restart the container.  
If you used `docker rm` to stop and start the container again, the data will be destroyed. If that is the case, we may need to create a standalone container to host MySQL server. 
Did I get you right? What do you think?

**Comment by gvancuts** [comment]
If I remember correctly, I stopped the container by pressing Ctrl-C on the terminal. I don't remember if I have tried with `docker stop` but I have never used `docker rm` for sure.

**Comment by gvancuts** [comment]
Ah, I think I understand what I was doing wrong... I was always starting the cloud using
```
$ sudo docker start run -p 3030:3000 -p 3031:4000 smarthome2cloud/smarthome-cloud
```
What I should do instead is either assign is a name or re-use the same container ID... my bad, my understanding of how containers work is obviously still largely incomplete.

I think it'd be good to add a note somewhere in our series of README.md to explain this subtlety. I'll turn this issue into an enhacement (rather than a bug) and get you ( @ichbinblau ) off the hook (although you are still more than welcome to submit PR to improve documentation).

**Comment by ichbinblau** [comment]
Yes, I usually use the command below to create the container.  The container process runs in the background.  
`docker run -d --name portal -p 3030:3000 -p 3031:4000 smarthome2cloud/portal:v1`
The steps have been documented [here](https://github.com/01org/SmartHome-Demo/tree/master/smarthome-web-portal/tools/docker) . But it seems a little out-of-dated. I will submit a PR to improve it.

**Comment by gvancuts** [comment]
8



Sent from my Samsung Galaxy smartphone.

> Yes, I usually use the command below to create the container. The container process runs in the background.

> docker run -d --name portal -p 3030:3000 -p 3031:4000 smarthome2cloud/portal:v1

> The steps have been documented here<https://github.com/01org/SmartHome-Demo/tree/master/smarthome-web-portal/tools/docker> . But it seems a little out-of-dated. I will submit a PR to improve it.

That would be nice of you... I had created issue #145 to track getting that part of the documentation updated.


Thanks!

**Comment by gvancuts** [comment]
User bug (i.e. I'm myself buggy)... I need to properly use container IDs when starting/stopping/restarting containers and things will be fine... closing this!
