### ISSUE TITLE
zjs-servers don't work after updating zephyr.js

### ISSUE THREAD

**Issue by qiuzhong** [01org/SmartHome-Demo#157]
After I update the [zephyr.js](https://github.com/01org/zephyr.js) to [44a5e6b](https://github.com/01org/zephyr.js/commit/44a5e6b8547af30583cc324d1263464e4fd76325), all the [SmartHome-Demo zjs-servers](https://github.com/01org/SmartHome-Demo/tree/master/ocf-servers/zjs-servers) samples are not working any more. The "ZJS Device" can be discovered and connected to the host, though.

I filed [zephyr.js issue#1255](https://github.com/01org/zephyr.js/issues/1255)

### My test environment:
* Ubuntu 16.04
* Zephyr SDK 0.9
* iot-rest-api-server: 0.4.1 (depends on iotivity-node 1.2.1-1)

**Comment by ttzeng** [comment]
It's a regression from the upstream project. Same kernel abort message even running the sample code samples/OcfServer.js in zephyr.js repository:
```
***** Kernel OOPS! *****
Current thread ID = 0xa800fae0
Faulting segment:address = 0x0008:0x400350f9
eax: 0x00000000, ebx: 0xa800daa0, ecx: 0x00000000, edx: 0x00000000
esi: 0x00000000, edi: 0xa800f980, ebp: 0xa800fbec, esp: 0xa800fbdc              
eflags: 0x246                                                                   
Fatal fault in essential thread! Spinning...
```

**Comment by uhofemei** [comment]
Could this be true for the native multi sensor code submitted in https://github.com/01org/SmartHome-Demo/pull/129 as well? I tried building the native multi sensor code against Zephyr and iotivity-constrained master and am not seeing the BLE device come up.

**Comment by qiuzhong** [comment]
I tried the native multi sensor sample. It turned out that the zephyr or iotivity-contained master can affect the native code as well. 

But in my test, the BLE device **Zephyr OCF Sensors** can be discovered and `bt0` on the host can be set up. However, it's very unstable. The OCF resources cannot be discovered via the iot-rest-api-rest-server, either.

**Comment by uhofemei** [comment]
I think the native multi server sample code needs to be rebased to work with the latest SDK and Zephyr and iotivity-constrained master. I was able to compile the code, but I'm not getting any output whatsoever using a serial connection.

**Comment by qiuzhong** [comment]
**Update**:
 Zephyr.js developers had closed [zephyr.js issue#1255](https://github.com/01org/zephyr.js/issues/1255) in [this PR](https://github.com/01org/zephyr.js/pull/1417). This fixed the one-sensor cases (led,js, temperature.js). However, the multi-sensor cases(multiserver.js, multiserver2.js) still don't work.

**Comment by gvancuts** [comment]
> Update:
> Zephyr.js developers had closed zephyr.js issue#1255 in this PR. This fixed the one-sensor cases (led,js, temperature.js). However, the multi-sensor cases(multiserver.js, multiserver2.js) still don't work.

Is it broken in the same way it was before? We should determine if https://github.com/01org/zephyr.js/issues/1255 needs to be re-opened or if a new issue should be filed.

Thanks!

**Comment by uhofemei** [comment]
This needs to be determined. IMHO being able to drive one sensor isn't sufficient for demo purposes. The bug I had opened that addresses the multi sensor use case is still open. https://github.com/01org/zephyr.js/issues/1237

**Comment by ttzeng** [comment]
I believe this issue has been transformed. This issue was caused by a segfault at the 1st place, and it's disappear after merging several commits few weeks ago. However the server will be lost from the REST API server report after few queries from the browser, which I think is different than [01org/zephyr.js#1237](01org/zephyr.js#1237), that one requires accesses from the web portal. IHO

**Comment by gvancuts** [comment]
> I believe this issue has been transformed. This issue was caused by a segfault at the 1st place, and it's disappear after merging several commits few weeks ago.
Thanks @ttzeng. I would suggest closing this issue in this case.

> However the server will be lost from the REST API server report after few queries from the browser, which I think is different than https://github.com/01org/zephyr.js/issues/1237, that one requires accesses from the web portal. IHO
Does that mean we need another issue filed in addition to https://github.com/01org/zephyr.js/issues/1237?

**Comment by ttzeng** [comment]
@gvancuts I believe [01org/zephyr.js#1237](https://github.com/01org/zephyr.js/issues/1237) filed by @uhofemei was referring the inaccessibility from the web portal (instead from REST API server), which is associated with #136 in this project. We definitely can track the interoperability between ZJS and web portal there. However, [01org/zephyr.js#1255](https://github.com/01org/zephyr.js/issues/1255) filed by @qiuzhong looks like different one, which some of resources are missing from the /oic/res queries, we may need to keep tracking of it IMHO

**Comment by gvancuts** [comment]
> @gvancuts I believe 01org/zephyr.js#1237 filed by @uhofemei was referring the inaccessibility from the web portal (instead from REST API server), which is associated with #136 in this project. We definitely can track the interoperability between ZJS and web portal there.
Let's not mix multiple issues in the same bug report, it will just create more confusion.

> However, 01org/zephyr.js#1255 filed by @qiuzhong looks like different one, which some of resources are missing from the /oic/res queries, we may need to keep tracking of it IMHO
It definitely looks like a different problem. That bug, however, is closed now. I believe it was closed on the basis that it has been *partially* resolved (i.e. resolved for a single resource but that's not sufficient for OCF servers hosting multiple resources). Can someone file a new bug to make sure this is tracked to a resolution?

**Comment by qiuzhong** [comment]
Close this issue as it should not confuse us any more . Since [01org/zephyr.js#1255](https://github.com/01org/zephyr.js/issues/1255) is closed, this issue should be closed. For the new bug, see [01org/zephyr.js #1428](https://github.com/01org/zephyr.js/issues/1428)
