### ISSUE TITLE
Describe prediction data set format

### ISSUE THREAD

**Issue by uhofemei** [01org/SmartHome-Demo#164]
Theresa,

When I opened the wiki for instructions how to upload the prediction data set you provided me with, I noticed we have no paragraph that described the data set CSV format. Can we add a paragraph that explains the meaning of the CSV order and values? Maybe we could also add a paragraph that explains where the data can be obtained.

**Comment by ichbinblau** [comment]
Hi, @uhofemei. The datasets have uploaded https://github.com/01org/SmartHome-Demo/pull/163/commits/ab440c12bd0f0bb7b066a8bf98839c7dbaac6fba  and the instructions have been improved [here] (https://github.com/01org/SmartHome-Demo/wiki/How-to-load-weather-and-power-prediction-data-automatically%3F). PTAL

**Comment by uhofemei** [comment]
This looks good to me. 👍
