### ISSUE TITLE
Update the value which is boolean to number for zjs-servers samples

### ISSUE THREAD

**Issue by wanghongjuan** [01org/SmartHome-Demo#172]
According to the latest GPIO specification in [zephyr.js/docs/gpio.md](https://github.com/01org/zephyr.js/blob/master/docs/gpio.md#web-idl), GPIOPin is defined as:
```
[NoInterfaceObject]
interface GPIOPin {
    number read();
    void write(number value);
    void close();
    attribute ChangeCallback onchange;
};
```
When invoke the method `write`, it required one number value, thought, the boolean value still can work well, but it is deprecated in zjs. Most of zjs-servers examples have this behavior.

The terminal show information as below when running [led.js](https://github.com/01org/SmartHome-Demo/blob/master/ocf-servers/zjs-servers/led.js) on A101 with commit [e3e4dde](https://github.com/01org/zephyr.js/commit/e3e4dde59c0595447107b391ede8f23c517b0ad3)
![boolean](https://user-images.githubusercontent.com/5309217/29206337-1d071820-7eb4-11e7-9e79-c8b323708468.png)

**Comment by ttzeng** [comment]
@wanghongjuan thanks for catching this bug, please review this resolution #173

**Comment by wanghongjuan** [comment]
Verified this issue with #173, it can not be reproduced.
