### ISSUE TITLE
Zjs-servers cannot work with iot-rest-api-server@0.6.0

### ISSUE THREAD

**Issue by qiuzhong** [01org/SmartHome-Demo#175]
## Description:
Recently there is a new iotivity-node release: 1.3.0, this is applied to the iot-rest-api-server 0.6 version.
However, after iot-rest-api-server is upgraded to 0.6.0, the REST API cannot discover the OCF resources from zjs-servers. The 6lowpan connection is still on. Meanwhile, this version iot-rest-api-server can work with the js-servers from #174 

## Steps:
1. Update [iot-rest-api-server](https://github.com/01org/iot-rest-api-server) to 0.6.0: `npm install iot-rest-api-server@0.6.0` and launch it.
2. Build the led.js zjs-server JS sample and and flash it to set up the 6lowpan.
3. Try to discover the OCF resources: `cd iot-rest-api-server/test && ./oic-get /res`

## Test comparison
| iot-rest-api-server | iotivity-node | zephyr.js | OCF resources |
| --- | --- | --- | --- |
| 0.5.0 | 1.2.1-1 | [06cce05](https://github.com/01org/zephyr.js/commit/06cce05c648c0ab253e3b432eb48e160731d6dc3) | Found | 
| 0.6.0 | 1.3.0-0 | [06cce05](https://github.com/01org/zephyr.js/commit/06cce05c648c0ab253e3b432eb48e160731d6dc3) | Not found |

**Comment by ttzeng** [comment]
It's the upstream bug ([#1481](https://github.com/01org/zephyr.js/issues/1481)), the A101 receives requests but no responses. Since the upstream sample code are also affected, let's wait the resolution from the ZJS engineering team.

**Comment by xiaoyu3x** [comment]
@ttzeng 
iot-rest-api-server@0.6.0 can retrieve resource when using commit [e789b4c](https://github.com/01org/iot-rest-api-server/commit/e789b4c7eeeaacbab83b597b9200716f93aa0e35) and new command `./oic-get /res?rt=***`, but still have some question existence.
e.g.
command `$ ./oic-get /a/led?di=***` can't be used.
There is a relative bug [#1548](https://github.com/01org/zephyr.js/issues/1548)

**Comment by xiaoyu3x** [comment]
hi, @qiuzhong 
By command `$ ./oic-get /a/led?di=***` can work normally, so please closed it.
Some issues also exist during retrieve resource and they will be tracked with [#1566](https://github.com/01org/zephyr.js/issues/1566)

**Comment by qiuzhong** [comment]
Closed
