### ISSUE TITLE
rgb_led only updated by 'PUT' request instead of 'POST' request

### ISSUE THREAD

**Issue by ttzeng** [01org/SmartHome-Demo#41]
According to OIC Resource Type Spec v1.1.0, Color RGB resources should get updates via HTTP POST request, but the changeHandler of rgb_led.js only get called on PUT requests.

**Comment by ttzeng** [comment]
Looks like an upstream bug that iotivity-node treats POST requests as resource create requests, PUT requests as resource change requests [1], how to deal with this kind of upstream bug?

[1] https://github.com/otcshare/iotivity-node/blob/master/lib/OicServer.js#L168-L200

**Comment by gvancuts** [comment]
I saw you filed the issue on the iotivity-node site directly (https://github.com/otcshare/iotivity-node/issues/83), this is the right course of action I believe, thanks!

**Comment by ttzeng** [comment]
Confirmed this issue has been fixed using iotivity-node with [commit 53249fc](https://github.com/otcshare/iotivity-node/tree/53249fcd62e69206d10f94efb04816f3de9b86e2)
