### ISSUE TITLE
Failed to get data of sensor in sample environmental-sensors

### ISSUE THREAD

**Issue by wanghongjuan** [01org/SmartHome-Demo#54]
## Reproduce Steps:
1. Connect BME280, Grove LCD and FTDI to Arduino 101 following the [README](https://github.com/01org/SmartHome-Demo/blob/master/sensors/environmental-sensors/README.md) file
2. Add debug message to file main.c
`x86/src/main.c`: Add some printk messages into “main” and “sensor_ipm_callback”
`arc/src/main.c`: Add some printk messages into “main”
3. Build arc/x86 application and flash them to Arduino 101, connect “Zephyr Environmental Sensor” using iPhone 5S with app nRP Connect.
Serial Output:
(Show the debug message in the “main” of x86/src/main.c, the other debug message doesn’t output, the LCD doesn’t light up.)
Connected

It seems doesn’t enter the function “sensor_ipm_callback”.

## Environment
**HW**: Arduino 101, BME 280, Grove LCD, iPhone 5S
**SW**:  Zephyr SDK(v0.8.2), Zephyr 1.5.0, [Sample](https://github.com/01org/SmartHome-Demo/tree/master/sensors/environmental-sensors), Ubuntu 14.04.1

**Comment by gvancuts** [comment]
@kiendinh , can you please take a look?

@wanghongjuan , could you share the specifics of the code changes you made?

I'll let @kiendinh confirm but I have a vague recollection that the serial output is not directly connected so unless there is an IPM set-up with the x86 it may be 'normal' that you don't see anything.

**Comment by kiendinh** [comment]
@wanghongjuan Could you please check if the ARC app was flashed correctly? It's normal that the custom printk messages should appear on the output log. You can check with other sample apps in the Zephyr source tree like the "hello world" to see if it works and go back to the ARC app again.

Please also check if the kconfig option "CONFIG_ARC_INIT=y" in the x86/prj.conf file is still the same. In case "CONFIG_ARC_INIT=n" the ARC app will not start and thus nothing will be shown on the output log.

@gvancuts The IPM for output log is basic in Zephyr and it should function normally as long as the ARC app runs.

**Comment by wanghongjuan** [comment]
Hi, @gvancuts Change code show as below: `x86/src/main.c`: insert `printk("Debug: sensor_ipm_callback");` to line 180 and `printk("Debug Bluetooth\n");` between line 229 and line 230. `arc/src/main.c`: insert `printk("debug bme280: %s\n", ipm);` between line77 and line 78, `printk("debug adc: %s\n", ipm);` between line 84 and line 85.
@kiendinh 
I try to restore the Arduino 101 to factory settings, and flash newt firmware for BLE and rebuild the arc and x86 applications to target devices. Get two results after run several times:
1. The backlight of the LCD is on, but show nothing. Show below information via serial cable(FTDI):
```
ipm_console0: 'Address 0x40039696'
ipm_consolefault in essential taing...'
ipm_console0: 'debug Exception vector: 0x00000003, cause code: 0x00000004, parameter 0x00000onsole0: '0'
ipm_coddress 0x40ipm_console0: 'Fatal fault in essential task ! Spinning...'
```
For the log `Failed to get BME280 sensor`, sometimes is exists. I don't know why, because using the same steps and environment.
2. The backlight of the LCD is on, show as the attachment picture and log information in terminal:
![lcd](https://cloud.githubusercontent.com/assets/5309217/20255680/989daa54-aa79-11e6-8973-710377589d64.JPG)
```
ipm_consoleDebug: sensor_ipm_callback0: 'Failed to fetch sample for BME280 sensor'
ipm_consoleDebug: sensor_ipm_callback0etch sample for BME280 sensor'
ipm_consoleDebug: sensor_ipm_callback0: 'Failed to fetch sample for BME280 sensor'
0 sensor'
ipm_consoleDebug: sensor_ipm_callback0: 'Failed to fetch sample for BME280 sensor'
ipm_consoleDebug: sensor_ipm_callback0: 'Failed to fetch sample for BME280 sensor'
ipm_consoleDebug: sensor_ipm_callback0: 'Failed to fetch sample for BME280 sensor'
ipm_consoleDebug: sensor_ipm_callback0: 'Failed to fetch sample for BME280 sensor'
ipm_consoleDebug: sensor_ipm_callback0: 'Failed to fetch sample for BME280 sensor'
ipm_consoleDebug: sensor_ipm_callback0: 'Failed to fetch sample for BME280 sensor'
ipm_consoleDebug: sensor_ipm_callback0: 'Failed to fetch sample for BME280 sensor'
ipm_consoleDebug: sensor_ipm_callback0: 'Failed to fetch sample for BME280 sensor'
ipm_consoleDebug: sensor_ipm_callback0: 'Failed to fetch sample for BME280 sensor'
ipm_consolesor_ipm_callback0: 'Failed toipm_consoleDebug: sensor_ipm_callback0: 'Failed to fetch sam280 sensor'
ipm_c: sensor_ipm_callbacked to fetch sample for BME280 sensor'
ipm_consoleDebug: sensor_ipm_callback0: 'Failed to fetch sam280 sensor'
ipm_consoleDebugpm_callbacked to fetch sample for BME280 sipm_consolsor_ipm_callback0: 'Failed to fetch sample for BME280 sensoripm_c0: 'Fail fetch samnsor_ipm'
ipm_consoleDebug: sensor_ipm_callback0: 'Failed to fetch sample for BME280 sensor'
ipm_consolallback0:k0: 'Faich sample fnsor_ipm_callback0:o fetch sample for BMr'
consoleDebuipm_callbacled to fetr'
ipm_callback0: 'Failed to fetch sample sor_ipm_caE280 sensor'
ipm_console0: 'Failed to fetch samplDebug: sensor_ipm_callbackDebug: sensor_ipm_callbackDebug: sensor_ipm_callbackDebug: sensor_ipm_callbackDe_ipm_callbipug: s'
ipm_consoleDebug: sensor_ipm_callback0: 'Failed to fetch sample for BME280 sensor'
_consoleDebug: sensor_ipm_callback0: 'Failed to fetch samplecallback0: 'Failed to fetch sBME280 sensipm_consoleDebug: sensor_ipm_callback0: 'Ftch sample for BM'
ipm_consoleDebug: scallback0: 'Failed to fetch sample for or'
ipm_consoleDebug: sensor_ipm_ 'Failed to fetch sample for BME280 sensor'
ipm_consoleDebug: sensor_ipm_callback0: 'Failed to fetch sample for BME280 sensor'
ipm_consoleDebug: sensor_ipm_ 'Failedample for BME280 senipm_consoleDebug: sensor_ipm_callback0: 'Failed to fetch sample for BME280 sensor'
ipm_consoleDebug: sensor_ipm_callback0: 'Failed to fetch sample for BME280 sensor'
ipm_consoleDebug: sensor_ipm_callback0: 'etch sampl0 sensor'
                                                            ipm_consensor_ipm: 'Failed to fetch sample forsor'
m_consoleDebug: sensor_ipm_callback0: 'Failed to fetch sample for BME280 sensor'
ipm_consoleDebug: sensor_ipm_callback0: 'Failed to fetch sample for BME280 sensor'
ipbug: sensoback0: 'etch sample for BME280 sensor'
ipm_consensor_ipm_callback0: 'Failedsample fornsor'
pm_consoleDebug: sensor_ipm_callFailed to fetch sample for BME2d to fetch  BME280 sensor'
iebug: sensor_ipm_callback0: 'Failed to e for BME2
ipm_co sensor_ipm_callback0: 'Failed to fetch sample for BME280 sensor'
ipm_consoleDor_ipm_cal: sensor_ipm_callback0: 'Failed to fetch sample for BME280 sensor'
```
It seems enter the function “sensor_ipm_callback”.

BTW, using the steps as above, restore other device Arduino 101, but this time the backlight of the LCD is off, get the results same as first time.

>> Please also check if the kconfig option "CONFIG_ARC_INIT=y" in the x86/prj_nimble.conf file is still the same and not modified. In case "CONFIG_ARC_INIT=n" the ARC app will not start and thus nothing will be shown on the output log.
The kconfig option is exists in file `x86/prj_nimble.conf`

**Comment by kiendinh** [comment]
How many BME280 modules do you have? There is some problem with the module so that it cannot read data from it. It would be good exchange with others to see if they work. If possible, please remove the LCD and keep only the BME280 so that the circuit becomes simpler since you don't need any pull-up circuit. Just connect the BME directly: SDL - SDL, SDA - SDA, GND - GND and 5V - Vin.

**Comment by wanghongjuan** [comment]
OK, I have two BME280 modules and re-run this sample following what you said, get the same result as before. There is one question need to confirm with you, should use `SCL` instead of `SDL`, is it right?

**Comment by wanghongjuan** [comment]
It is confused that get below log information when re-run this sample without connecting sensor BME280
```
ipm_console0: '0'
ipm_console0: 'Address 0x40039696'
ipm_console0: 'Fatal fault in essential task ! Spinning...'
```
So I try to run sample [bmg160](https://github.com/01org/zephyr/tree/master/samples/sensor/bmg160) in zephyr project without connecting sensor BMG160, get a different result log:
```
[BMG160] [DBG] bmg160_init: Failed to read chip id.
```

**Comment by kiendinh** [comment]
Please excuse me for the typos. It's SCL.
Different sensors are being initialized differently so the error messages may be not the same.

I hope that the Arduino 101 firmware is functioning correctly. Can you try to replace the Arduino or re-flash the firmware again?

**Comment by wanghongjuan** [comment]
This time using Genuino 101 replace the Arduino 101, and restore the Genuino to factory settings, flash the Newt BLE firmware and build the applications, but get the log message like `ipm_console0: 'Failed to get BME280 sensor'`. The sensor is connected following the method that you mentioned.

**Comment by kiendinh** [comment]
The error happens when it cannot find and initialize the BME280 module. Please check your setup and maybe the BME280. Here is my simple setup for your information.

![20161115_162942](https://cloud.githubusercontent.com/assets/11462046/20297015/89b431ec-ab51-11e6-9b31-dae8cbe4c05a.jpg)

**Comment by wanghongjuan** [comment]
Thanks for setup it again. I am using this sensor, please refer the attachment. I have been confirmed it with you, the sensor should can be used in this sample. Maybe this sensor can not work in this case.
<img width="213" alt="bme280" src="https://cloud.githubusercontent.com/assets/5309217/20299112/60bc5c30-ab54-11e6-97b0-e676b7e15879.PNG">

**Comment by kiendinh** [comment]
Please see the link below. It's different breakout but basically can be used with I2C and SPI like your board. The wiring for I2C is similar to what you're using.

https://learn.adafruit.com/adafruit-bme280-humidity-barometric-pressure-temperature-sensor-breakout/wiring-and-test

**Comment by wanghongjuan** [comment]
Hi, @kiendinh Thanks for your confirmation again. Good news is coming, the sample is works now. The LCD can show the values of temperature, humidity and pressure, no including UV. I think the problem is the sensor connection is too loose, so fix the pins to the sensor and it works. 
BTW, it seems that iPhone 5S can not get the value. But Nexus 5 can show all values. Can you reproduce this scenario? There is one thing confused me that the value of UV sensor is 255, I think the value is unbelievable, maybe my sensor is broken. I am indoors. Can you tell what's your UV value?

**Comment by wanghongjuan** [comment]
Do you have any solution that can resolve how to get the sensor data on home gateway? The module `noble` has been install via `npm install noble`, and launch server script via command `export NODE_DEBUG=environmental_sensor;node environment_sensor.js`, then it is hang and show below log :
```
ENVIRONMENT_SENSOR 442: Create environmental sensor resource.
ENVIRONMENT_SENSOR 442: register() resource successful
```
I am using [Edison](https://software.intel.com/en-us/iot/hardware/edison) as gateway which supports BLE.  Is there anything missing cause the server script can not get data? It seems doesn't scan the BLE.

**Comment by gvancuts** [comment]
Hi @wanghongjuan , as far as I remember, there are problems with BLE on Edison. Can you try another platform (with a different Bluetooth dongle) to test this? @kiendinh can provide more details but he's away from his desk for a couple of days so he may not see this immediately.

**Comment by wanghongjuan** [comment]
Yes, I also run it on Joule 570x with [image#192](https://download.ostroproject.org/builds/ostro-os-xt/2016-11-13_21-27-36-build-192/images/intel-corei7-64/ostro-xt-image-noswupd-benchmark-qa-intel-corei7-64-2016-11-13_21-27-36-build-192.dsk.xz), it has same problem as Edison.

**Comment by kiendinh** [comment]
It seems that the bluetooth on your platform is not yet enabled. Pls set it on with "rfkill unblock bluetooth" and check with hciconfig if's unlocked and running.

**Comment by wanghongjuan** [comment]
@kiendinh I think that it works now, display log information as below:
```
root@intel-corei7-64:~# node environmental_sensor.js >log
ENVIRONMENTAL_SENSOR 6977: Create environmental sensor resource.
ENVIRONMENTAL_SENSOR 6977: register() resource successful
ENVIRONMENTAL_SENSOR 6977: on -> stateChange
ENVIRONMENTAL_SENSOR 6977: on -> scanStart
ENVIRONMENTAL_SENSOR 6977: on -> discover: {"id":"e9522d00fb1e","address":"e9:52:2d:00:fb:1e","addressType":"random","connectable":true,"advertisement":{"serviceData":[],"serviceUuids":["181a"],"solicitationServiceUuids":[],"serviceSolicitationUuids":[]},"rssi":-74,"state":"disconnected"}
ENVIRONMENTAL_SENSOR 6977: on -> discover: {"id":"e9522d00fb1e","address":"e9:52:2d:00:fb:1e","addressType":"random","connectable":true,"advertisement":{"localName":"Zephyr Environmental Sensor","serviceData":[],"serviceUuids":["181a"],"solicitationServiceUuids":[],"serviceSolicitationUuids":[]},"rssi":-74,"state":"disconnected"}
ENVIRONMENTAL_SENSOR 6977: on -> scanStop
ENVIRONMENTAL_SENSOR 6977: on -> connect
ENVIRONMENTAL_SENSOR 6977: on -> ESS service discovery
ENVIRONMENTAL_SENSOR 6977: Humidity =  45.69 %
ENVIRONMENTAL_SENSOR 6977: Pressure =  1048.559 hPa
ENVIRONMENTAL_SENSOR 6977: Temperature notification ON
ENVIRONMENTAL_SENSOR 6977: Humidity notification ON
ENVIRONMENTAL_SENSOR 6977: Pressure notification ON
ENVIRONMENTAL_SENSOR 6977: UV Index notification ON
ENVIRONMENTAL_SENSOR 6977: UV Index =  255
ENVIRONMENTAL_SENSOR 6977: Temperature =  22.09 celcius
ENVIRONMENTAL_SENSOR 6977: Humidity =  45.66 %
ENVIRONMENTAL_SENSOR 6977: Pressure =  1048.557 hPa
ENVIRONMENTAL_SENSOR 6977: UV Index =  255
ENVIRONMENTAL_SENSOR 6977: Temperature =  22.1 celcius
ENVIRONMENTAL_SENSOR 6977: Humidity =  45.65 %
ENVIRONMENTAL_SENSOR 6977: Pressure =  1048.566 hPa
ENVIRONMENTAL_SENSOR 6977: UV Index =  255
ENVIRONMENTAL_SENSOR 6977: Temperature =  22.1 celcius
ENVIRONMENTAL_SENSOR 6977: Humidity =  45.66 %
ENVIRONMENTAL_SENSOR 6977: Pressure =  1048.565 hPa
ENVIRONMENTAL_SENSOR 6977: UV Index =  255
ENVIRONMENTAL_SENSOR 6977: Temperature =  22.1 celcius
ENVIRONMENTAL_SENSOR 6977: Humidity =  45.65 %
ENVIRONMENTAL_SENSOR 6977: Pressure =  1048.554 hPa
ENVIRONMENTAL_SENSOR 6977: UV Index =  255
```
About the data on iPhone 5S and UV sensor that I have mentioned, can you please help to confirm them? Thanks.

**Comment by kiendinh** [comment]
I used to check on my iPhone 5s, and it worked fine. The UV index value was 0 or 1.

**Comment by wanghongjuan** [comment]
Does the iPhone need to specific setting? I used two iPhones to test it, got the same result as below picture:
<img width="264" alt="untitled" src="https://cloud.githubusercontent.com/assets/5309217/20417241/043b7540-ad7f-11e6-8f75-f1a977dbda90.png">

**Comment by kiendinh** [comment]
Have you clicked on the buttons on the right side? One for read, and one for notification?

**Comment by wanghongjuan** [comment]
Yes, but no response.

**Comment by kiendinh** [comment]
I have no clue. It's rather an issue in the iPhone 5S and nRF Connect app side. At least you have the nRF Connect app working on the Android. This is out of the scope of the project.

**Comment by wanghongjuan** [comment]
OK, thanks.
