### ISSUE TITLE
The data of BME280 in LCD is different from the data in the app nRF Connect and ocf server

### ISSUE THREAD

**Issue by wanghongjuan** [01org/SmartHome-Demo#59]
Following this [guide](https://github.com/01org/SmartHome-Demo/blob/master/sensors/environmental-sensors/README.md) for sample sensors/environment-sensors to setup this sample, and it works now. I noticed that get the data of pressure from BME280 in RGB LCD is `104.450 kPa`, the data is `104450.3 kPa` in nRF Connect, the data is `1044.503 hPa`  in `environmental_sensors.js` . The value and unit are different.

**Comment by kiendinh** [comment]
Can you confirm again the unit value in nRF Connect? Is it in Pa or kPa?

**Comment by wanghongjuan** [comment]
Oh, it is Pa. Does this representation have any special meaning? Since they are using different unit.

**Comment by kiendinh** [comment]
Well, hPa = 100 Pa, kPa = 1000 Pa. They are all the same. :)

**Comment by wanghongjuan** [comment]
Yes, I understand that. Thanks.
