### ISSUE TITLE
DC Power Meter BLE service is not reader-friendly for Bluetooth clients.

### ISSUE THREAD

**Issue by qiuzhong** [01org/SmartHome-Demo#65]
DC Power Meter now supports BLE connection. When a Bluetooth app (nRF Connect, for example) connects to the DC Power Meter "Zephyr Power Meter" BLE service, the screenshot is like this:
![screenshot_20161207-031352](https://cloud.githubusercontent.com/assets/11829497/20958324/0935451a-bc90-11e6-825d-5697f25fb70b.png)

There are two problems:
1. The title of the service is "Unknow service", not "Zephyr DC Power Meter" as expected. The two properties are "Unknown Characteristic", not "Consumption Power" and "Solar Power" as expected.
2. The values of the two properties are not human-readable. For example, pressing the "Download" button of the a properties may return value 0xA0-0F-00-00, while the Grove LCD displays 4 mW. The latter is the return value after processing the raw value 0xA00F0000 in the code. They're equivalent in a way. But the former is not human-readable.

**Comment by kiendinh** [comment]
This is not an issue. The DC power meter is not designed to be used with phones. An application for Android or iOS needs to be developed for that purpose.

**Comment by qiuzhong** [comment]
I understand this feature is not necessary.

Since the environmental sensor app supports to display the sensor values friendly in mobile clients, I wonder if the DC Power Meter can also support this feature just like environmental sensor. In case the gateway is not available or the Bluetooth feature of the gateway is not available, it will be helpful to assure the DC Power Meter BLE service can work well via a Bluetooth client and don't waste time on the DC Power Meter part. And it will also help locate where the problem could be in the IoT environment when power-uart.js doesn't work.

**Comment by kiendinh** [comment]
The environmental sensor uses the standard BLE profiles that the phones support and thus can work with them. However, the power meter uses custom profiles. So in order to make it work friendly with the phone, applications which support those need to be developed.

**Comment by qiuzhong** [comment]
The explanation is convictive. Thank you!
