### ISSUE TITLE
zero value for solar/temperature/illuminance sensor data not updated

### ISSUE THREAD

**Issue by qiuzhong** [01org/SmartHome-Demo#68]
When parsing data after REST client getting the sensor data via REST API, there's something wrong with the condition to update data when the sensor data happen to be 0. For example, the [solar panel data parsing](https://github.com/01org/SmartHome-Demo/blob/master/smarthome-web-portal/CeleryTask/managers/data_manager.py#L101) is represented as:
```
                if sensor == 'solar':
                    new_tilt = data.get('properties').get('tiltPercentage')
                    if new_tilt:
                        content.update({
                            'tiltpercentage': new_tilt,
                            'lcd_first': data.get('properties').get('lcd1'),
                            'lcd_second': data.get('properties').get('lcd2'),
                        })
                        # add_method(content)
                        print 'update tilt percentage: {}'.format(str(add_method(content)))
                    else:
                        print "Unable to get tilt percentage."
```

Here, <code>new_tilt</code> may get a value of 0, which is the initial value when creating solar OCF resources. Unfortunately, in Python, both <code>bool(0)</code> and <code>bool(None)</code> return False. Thus, when the tiltPercentage is 0, content will not update. 
This may cause the following behavior:
- The browser may not display the resource even it exists. This happened in my tests when the solar panel resource was created. The log said: 
  > Unable to get tilt percentage.

  After changing the tiltPercentage to a non-zero value via an OCF client, the solar panel resource could show up in browser.

- In browser, the tiltPercentage of solar panel will never be 0. Not sure if this is reasonable.

This issue also exists in temperature and illuminance resources. I think for temperature data, 0 degree in Celsius is reasonable and should update.

**Comment by qiuzhong** [comment]
@ichbinblau , PTAL

**Comment by ichbinblau** [comment]
@qiuzhong good catch. I will fix it in the next PR.

**Comment by gvancuts** [comment]
Can you include a keyword to automatically close this when you do a Pull Request that should solve the issue - see https://help.github.com/articles/closing-issues-via-commit-messages/

I'd suggest to use "Fix #68"

**Comment by ichbinblau** [comment]
@gvancuts I have updated the commit message for the PR #52 including "Fixed #68."

**Comment by qiuzhong** [comment]
Tested & Verified on current latest commit id [fd4e84f](https://github.com/01org/SmartHome-Demo/commit/fd4e84f4bca60bbc15a59553b8eba06b1c9e549e)
This bug is not reproduced now.

For web portal back-end, the sensor data can be updated when values are zero.
For the web browser, these sensors can be displayed when values are zero as well.

**Comment by gvancuts** [comment]
Thanks @qiuzhong !
