### ISSUE TITLE
History page data is not filtered by the gateway of current user

### ISSUE THREAD

**Issue by qiuzhong** [01org/SmartHome-Demo#74]
For the smarthome-web-portal web app, each user is associated with a gateway. Currently, there are two users and two gateways pre-built:  dev account for lab gateway and ostro for demo.
The BEFORE panel should display the sensor history data of the gateway of the current user. 

However, when login via ostro user account, the BEFORE panel can still display the history data of sensors even gateway demo is not available.
In fact, the history data is from gateway lab and should not be displayed for user ostro.

At [the back-end](https://github.com/01org/SmartHome-Demo/blob/master/smarthome-web-portal/SHProject.py#L75), "gateway_id" is not passed as a parameter to the function <code>_get_historical_data</code>. The sensor history data is not filtered by the gateway of current user when querying it.

**Comment by qiuzhong** [comment]
@ichbinblau

**Comment by qiuzhong** [comment]
Tested & Verified on current latest commit id [fd4e84f](https://github.com/01org/SmartHome-Demo/commit/fd4e84f4bca60bbc15a59553b8eba06b1c9e549e)
This bug is not reproduced now.

When login with different users ( map to different gateways ), the "BEFORE" panel only displays the sensor history of gateway associated with the current user.

**Comment by gvancuts** [comment]
Thanks @qiuzhong
