### ISSUE TITLE
Admin Portal: introduce an 'Add User' function

### ISSUE THREAD

**Issue by gvancuts** [01org/SmartHome-Demo#78]
We should introduce an 'Add User' function in the Admin Portal. The user will typically have the following attributes (at a minimum):
- Full Name
- Location (address)
- Mobile Phone (for a hypothetical, future feature enabling text messages)
- Gateway assigned (a drop-down menu should display the list of Gateways that already exist.

Note: deleting users shall be fixed as part of this (see #49 for details on current limitation)
Note2: new gateways shall be created via the 'Gateways' section of the Admin Portal (the function is in place already)

**Comment by mjkadera** [comment]
The web portal side will have the ability to have multiple users connect to multiple gateways. The energy dashboard will show all gateways setup in the portal that were registered.

In the future we could add a feature to check if the gateway is active or not.

**Comment by gvancuts** [comment]
PR #125 was merged... closing this issue!
