### ISSUE TITLE
Cloud Portal: generic widget that can display any OCF server available

### ISSUE THREAD

**Issue by gvancuts** [01org/SmartHome-Demo#91]
We should have a generic widget that would allow to visualize *any* kind of OCF server that has been discovered. It's understood that interacting with such OCF server will not be as user-friendly as with other, known OCF server types. The ability to exchange information (raw JSON payload) would be desirable).

**Comment by gvancuts** [comment]
Hi @ichbinblau , is it possible to have this implemented in the next 10 days?

@mjkadera , FYI

**Comment by ichbinblau** [comment]
Hi, @gvancuts . Within 10 days, I can create a generic widget to simply reflect the json data.  It shows the fields returned from the ocf server and list them in the widget. But it would take more time to categorize the sensor, eg. alerts type or just status updates. And the sensor would not be controllable cos the http protocol has to be pre-defined somewhere and some fields are not allowed to be updated sometimes.  Is it good for you?

**Comment by gvancuts** [comment]
I think it's OK if the device cannot be classified in the first version. Isn't there a way we can send a hand-crafted message to interact with any device?

**Comment by ichbinblau** [comment]
Hi, @gvancuts. In first version, I plan to design the widget like the screenshot below:
<img width="208" alt="capture" src="https://cloud.githubusercontent.com/assets/8187638/22878642/8414c14c-f215-11e6-9f7d-11f789d1dc7d.PNG">
The widget illustrates all the json data as a data table. Users are allowed to update the resource properties (send http post to ocf server) by clicking on the edit button.  When the portal detects that one resource type is unknown, it is categorized as generic type automatically with basic data visualization and control functions.  Do you think it is good to start with?

**Comment by gvancuts** [comment]
Thanks @ichbinblau , this looks good to me!

Could you also print out the `"n"` string (read-only) on the widget? Perhaps enclosing it in brackets just after the "Generic resource" widget title? E.g. Generic resource ("Smart Solar Panel"). That would make it generic but yet a little more easily identifiable when there are multiple of those. Similarly, could the device ID be printed out somewhere (so it can be re-used by the user)?

@poussa , thoughts?

**Comment by ttzeng** [comment]
@ichbinblau How will you validate the data entered by the user are in the correct data types? If the portal updates the data of the wrong data type, it might cause problems in the receiving end.

**Comment by ichbinblau** [comment]
@ttzeng, this is a good question. There is no effective way to validate the data type as the data type is not described somewhere if the resource is not pre-defined.  What I can filter from the fronted is to prevent from some malicious attacks, such as cross-site scripting, sql injection etc.  Only Json format is permitted.  It mostly depends on the server to validate the data.  Does the server have the input data validation?

**Comment by ichbinblau** [comment]
Hi, @gvancuts.  It seems that the "n" string is not exposed by the Rest API. What we can get is the id of the resource. 
<img width="109" alt="capture1" src="https://cloud.githubusercontent.com/assets/8187638/22911879/213b6c46-f29d-11e6-88f3-c50e578b784f.PNG">
<img width="215" alt="capture" src="https://cloud.githubusercontent.com/assets/8187638/22911883/27c23996-f29d-11e6-8508-a4f360ce9862.PNG">

**Comment by gvancuts** [comment]
The parameter is returned when doing a device discovery (`oic\d`), I don't know however if there is another (better?) way.

**Comment by ttzeng** [comment]
AFAIK, that's the name of the device hosting the resource, not the name of the resource.

**Comment by gvancuts** [comment]
Ah! Thanks for the clarification @ttzeng. Assuming each resource would have its own widget, I still think it'd be valuable to add the name of the device hosting it to the widget.

**Comment by ttzeng** [comment]
The 'n' property of a resource is read only, unless we have implemented the Configuration /oic/con https://github.com/01org/SmartHome-Demo/issues/71

**Comment by gvancuts** [comment]
That's fine in my opinion, I'm just looking for a way to somewhat more easily identify what this "Generic resource" is, especially in case there are multiple instances of such resources/devices in the network.

**Comment by gvancuts** [comment]
I believe this was completed and merged, wasn't it @ichbinblau ?

**Comment by ichbinblau** [comment]
Yes, a generic widget has been created for generic sensors.  If there is any improvements and requirements, we can open another issue for it.

**Comment by gvancuts** [comment]
Thanks, closing this then.
